# yaml-language-server: $schema=https://json.schemastore.org/lazygit.json
# Lazygit config, docs: <https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md>
git:
  # Use delta as the pager.
  pagers:
    - colorArg: always
      pager: delta --dark --paging=never
gui:
  # Default to line-wise staging (the primay thing I use lazygit for)
  useHunkModeInStagingView: false
