# yaml-language-server: $schema=https://json.schemastore.org/lazygit.json
# Lazygit config, docs: <https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md>
git:
  # Use delta as the pager.
  pagers:
    - colorArg: always
      pager: delta --dark --paging=never
